//go:generate go run main.go
package main

import (
	"bytes"
	_ "embed"
	"go/format"
	"io"
	"os"
	"text/template"
)

//go:embed imports.go.tmpl
var tsImports string

//go:embed doTask.go.tmpl
var tsDoTask string

//go:embed run.go.tmpl
var tsRun string

//go:embed writeOutputCsvRow.go.tmpl
var tsWriteOutputCsvRow string

//go:embed resultsHandler.go.tmpl
var tsResultsHandler string

//go:embed metricRecord.go.tmpl
var tsMetricRecord string

func parse(s string) *template.Template {
	t, err := template.New("").Parse(s)
	if err != nil {
		panic(err)
	}
	return t
}

func renderer[T any](w io.Writer) func(*template.Template, []T) {
	return func(t *template.Template, data []T) {
		if len(data) == 0 {
			if err := t.Execute(w, nil); err != nil {
				panic(err)
			}
			if _, err := w.Write([]byte("\n")); err != nil {
				panic(err)
			}
			return
		}

		for _, d := range data {
			if err := t.Execute(w, d); err != nil {
				panic(err)
			}
			if _, err := w.Write([]byte("\n")); err != nil {
				panic(err)
			}
		}
	}
}

func main() {
	const dstFile = "../../../gen_strategies.go"

	defer func() {
		if r := recover(); r != nil {
			defer panic(r)
			os.Remove(dstFile)
			return
		}
	}()

	f, err := os.Create(dstFile)
	if err != nil {
		panic(err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			v := any(err)
			if r := recover(); r != nil {
				v = r
			}
			panic(v)
		}
	}()

	var buf bytes.Buffer

	_, err = buf.WriteString(`// Code generated by ./internal/cmd/generate/main.go DO NOT EDIT.` + "\n\n")
	if err != nil {
		panic(err)
	}

	// create imports section of source code
	{
		render := renderer[any](&buf)

		render(parse(tsImports), nil)
	}

	// render metricRecord strategies
	{
		t := parse(tsMetricRecord)

		type cfg struct {
			RetriesEnabled    bool
			MaxTasksGTZero    bool
			PercentileEnabled bool
			VarianceEnabled   bool
		}

		render := renderer[cfg](&buf)

		render(t, []cfg{
			{RetriesEnabled: true, MaxTasksGTZero: true, PercentileEnabled: true, VarianceEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: true, PercentileEnabled: true, VarianceEnabled: false},
			{RetriesEnabled: true, MaxTasksGTZero: true, PercentileEnabled: false, VarianceEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: true, PercentileEnabled: false, VarianceEnabled: false},
			{RetriesEnabled: true, MaxTasksGTZero: false, PercentileEnabled: true, VarianceEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: false, PercentileEnabled: true, VarianceEnabled: false},
			{RetriesEnabled: true, MaxTasksGTZero: false, PercentileEnabled: false, VarianceEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: false, PercentileEnabled: false, VarianceEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: true, PercentileEnabled: true, VarianceEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: true, PercentileEnabled: true, VarianceEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: true, PercentileEnabled: false, VarianceEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: true, PercentileEnabled: false, VarianceEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: false, PercentileEnabled: true, VarianceEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: false, PercentileEnabled: true, VarianceEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: false, PercentileEnabled: false, VarianceEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: false, PercentileEnabled: false, VarianceEnabled: false},
		})
	}

	// render doTask strategies
	{
		t := parse(tsDoTask)

		type cfg struct {
			RetriesEnabled bool
			MetricsEnabled bool
		}

		render := renderer[cfg](&buf)

		render(t, []cfg{
			{RetriesEnabled: true, MetricsEnabled: true},
			{RetriesEnabled: true, MetricsEnabled: false},
			{RetriesEnabled: false, MetricsEnabled: true},
			{RetriesEnabled: false, MetricsEnabled: false},
		})
	}

	// render run strategies
	{
		t := parse(tsRun)

		type cfg struct {
			RetriesEnabled bool
			MaxTasksGTZero bool
			MetricsEnabled bool
		}

		render := renderer[cfg](&buf)

		render(t, []cfg{
			{RetriesEnabled: true, MaxTasksGTZero: true, MetricsEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: true, MetricsEnabled: false},
			{RetriesEnabled: true, MaxTasksGTZero: false, MetricsEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: false, MetricsEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: true, MetricsEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: true, MetricsEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: false, MetricsEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: false, MetricsEnabled: false},
		})
	}

	// render writeOutputCsvRow strategies
	{
		t := parse(tsWriteOutputCsvRow)

		type cfg struct {
			RetriesEnabled    bool
			MaxTasksGTZero    bool
			PercentileEnabled bool
			VarianceEnabled   bool
		}

		render := renderer[cfg](&buf)

		render(t, []cfg{
			{RetriesEnabled: true, MaxTasksGTZero: true, PercentileEnabled: true, VarianceEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: true, PercentileEnabled: true, VarianceEnabled: false},
			{RetriesEnabled: true, MaxTasksGTZero: true, PercentileEnabled: false, VarianceEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: true, PercentileEnabled: false, VarianceEnabled: false},
			{RetriesEnabled: true, MaxTasksGTZero: false, PercentileEnabled: true, VarianceEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: false, PercentileEnabled: true, VarianceEnabled: false},
			{RetriesEnabled: true, MaxTasksGTZero: false, PercentileEnabled: false, VarianceEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: false, PercentileEnabled: false, VarianceEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: true, PercentileEnabled: true, VarianceEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: true, PercentileEnabled: true, VarianceEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: true, PercentileEnabled: false, VarianceEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: true, PercentileEnabled: false, VarianceEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: false, PercentileEnabled: true, VarianceEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: false, PercentileEnabled: true, VarianceEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: false, PercentileEnabled: false, VarianceEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: false, PercentileEnabled: false, VarianceEnabled: false},
		})
	}

	// render resultsHandler strategies
	{
		t := parse(tsResultsHandler)

		type cfg struct {
			RetriesEnabled    bool
			MaxTasksGTZero    bool
			PercentileEnabled bool
			VarianceEnabled   bool
		}

		render := renderer[cfg](&buf)

		render(t, []cfg{
			{RetriesEnabled: true, MaxTasksGTZero: true, PercentileEnabled: true, VarianceEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: true, PercentileEnabled: true, VarianceEnabled: false},
			{RetriesEnabled: true, MaxTasksGTZero: true, PercentileEnabled: false, VarianceEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: true, PercentileEnabled: false, VarianceEnabled: false},
			{RetriesEnabled: true, MaxTasksGTZero: false, PercentileEnabled: true, VarianceEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: false, PercentileEnabled: true, VarianceEnabled: false},
			{RetriesEnabled: true, MaxTasksGTZero: false, PercentileEnabled: false, VarianceEnabled: true},
			{RetriesEnabled: true, MaxTasksGTZero: false, PercentileEnabled: false, VarianceEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: true, PercentileEnabled: true, VarianceEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: true, PercentileEnabled: true, VarianceEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: true, PercentileEnabled: false, VarianceEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: true, PercentileEnabled: false, VarianceEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: false, PercentileEnabled: true, VarianceEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: false, PercentileEnabled: true, VarianceEnabled: false},
			{RetriesEnabled: false, MaxTasksGTZero: false, PercentileEnabled: false, VarianceEnabled: true},
			{RetriesEnabled: false, MaxTasksGTZero: false, PercentileEnabled: false, VarianceEnabled: false},
		})
	}

	// // for debugging
	// _, err = f.Write(buf.Bytes())
	// if err != nil {
	// 	panic(err)
	// } else {
	// 	return
	// }

	b, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}

	_, err = f.Write(b)
	if err != nil {
		panic(err)
	}
}
